# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzzhQ6MEmlhR2v6p4UM3vtf-eBIG7KCD
"""

import pandas as pd

# 1. DataFrame yaratish
data = {
    'Ism': ['Muso', 'SHohruh', 'Boburbek'],
    'Yoshi': [22, 31, 30],
    'Shahar': ['Toshkent', 'Navoiy', 'Namangan']
}
df = pd.DataFrame(data)

# 2. Ma'lumotlarni ko'rish
print(df)

# 3. Filtrlash
young_people = df[df['Yoshi'] < 30]
print("30 yoshdan kichiklar:\n", young_people)

# 4. O'zgartirish
df['Yoshi'] += 1  # Har bir shaxsning yoshini 1 ga oshirish
print("Yangilangan DataFrame:\n", df)

# 5. CSV formatda saqlash
df.to_csv('data.csv', index=False)